server {
    listen 80;
    server_name localhost;

    # This line is the "Dictionary" that tells Nginx what HTML, JS, and CSS are
    include /etc/nginx/mime.types;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # We still need this for Replicad to work
    types {
        application/wasm wasm;
    }
}